<?php

/**
 * @file
 * Generate custom thumbnails for media entities.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * {@inheritDoc}
 */
function media_thumbnails_mapper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.media_thumbnails_mapper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Media Thumbnails Mapper module generates thumbnails for media entities. If passed a file xyz.pdf, an input image of xyz.pdf.jpg is assued to exist as input for the thumbnail') . '</p>';
      return $output;
  }
}
